### ISSUE TITLE
How to USe

### ISSUE THREAD

**Issue by milnerjames** [Symbolexe/AutoGather#1]
Please what are the correct input i'm getting
![Screenshot (1)](https://github.com/Symbolexe/AutoGather/assets/65741829/66be4ab7-983c-4d22-93c6-e52a10424ec2)
 error when i select a number

**Comment by milnerjames** [comment]
![Screenshot (3)](https://github.com/Symbolexe/AutoGather/assets/65741829/be4cbc2e-9051-433b-a08f-bba21949f9be)

**Comment by hamiidnaserii** [comment]
Hello dear friend, you gave the wrong amount. How do you expect the right answer? He asked you for your target. You have to give it a url or an ip and nothing else. I tested and the tool worked fine

![Screenshot 2024-02-18 at 1 32 27 in the afternoon](https://github.com/Symbolexe/AutoGather/assets/63211880/1ffe4f96-ed2b-4f9e-8f54-193d7c94fc50)
